# -*- coding: utf-8 -*-
"""OCR_Bangalore_Electricity_Bill.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/srinivasanibmbangalore/Deep-Learning2/blob/master/OCR_Bangalore_Electricity_Bill.ipynb
"""

! apt install tesseract-ocr
! apt install libtesseract-dev

!pip install pytesseract

import cv2
import numpy as np
from google.colab.patches import cv2_imshow
from PIL import Image, ImageEnhance, ImageFilter

!curl -o bill.jpg https://www.aamindia.com/wp-content/uploads/2014/02/Bescom-Bill-Payment-Find-Account-ID.jpg?x97180

img = cv2.imread('bill.jpg', cv2.IMREAD_UNCHANGED)
type(img)
cv2_imshow(img)

text = pytesseract.image_to_string(img, lang='eng')
print (text)